#+------------------------------------------------------------------------------------------------------+#
#|                                                                                                      |#
#|                                                                                                      |#
#|                                            J P R E M I U M                                           |#
#|                                        C O N F I G U R A T I O N                                     |#
#|                                                                                                      |#
#|                                                                                                      |#
#+------------------------------------------------------------------------------------------------------+#

version: 'CLEARED-Bungee-1.8.0'

# JPremium currently supports only MySQL databases.
# When JPremium cannot connect your database, issues are always produced by your database or the connection between your BungeeCord and your database!
# If you have issues, please see this wiki page: https://github.com/Jakubson/JPremiumCleared/wiki#database-issues
storageHost: ''
storagePort: 3306
storageDatabase: ''
storageUser: ''
storagePassword: ''
storageProperties: [useSSL=true, verifyServerCertificate=true]

# Storage connection pool settings.
# Do not change these settings unless you know what you are doing!
connectionPoolSize: 10
connectionPoolIdle: 10
connectionPoolTimeout: 5000
connectionPoolLifetime: 1800000

# The mail server which is used to send mails.
# Please enter data only if you want to use the passwords recovery system.
# If you do not want to use it, please also disable the change mail address and recovery password commands.
mailHost: ''
mailPort: 25
mailUser: ''
mailPassword: ''
mailUseTLS: true

# The access token which is used to verify connections on your Spigot servers whether connections come from your BungeeCord.
# Please enter fully random unique value! Not: 'your-server-name-jpremium'!
# The same token you have to enter on all your Spigot servers.
accessToken: ''

# The limbo server names in your BungeeCord network.
# Not authorised players are redirected to the servers.
limboServerNames: [limbo]

# The main server names in your BungeeCord network.
# Authorised players are redirected to the servers.
mainServerNames: [main]

# What unique ids should JPremium assign for players.
# There are three options and each option has different restrictions.
# It is not recommended changing this option when some players are already registered.
# For more information, please read this wiki page: https://github.com/Jakubson/JPremiumCleared/wiki#fixed-unique-ids
uniqueIdsType: FIXED

# Should JPremium force new players to register on your server, website or both side.
# There are three options to choose: 0 - server, 1 - server and website, 2 - website.
registerOnWebsite: 0

# Should JPremium register new premium players.
# When it is enabled, cracked players with premium nickname cannot join to your server.
registerPremiumUsers: true

# Should JPremium redirect players to their last server where they were before quit.
lastServerRedirection: true

# The server names in your BungeeCord network.
# Players will not be redirected to the servers as their last server.
lastServerRestrictions: []

# Should JPremium redirect players to one of the main server from the server which is shutting down.
disconnectRedirection: true

# Should JPremium disconnect cracked players who enter wrong password during login.
disconnectWhenWrongPassword: false

# Should JPremium recognise Bedrock players and alters their unique ids to bedrock.
# Works only when you install GeyserMC and Floodgate on your server.
# For more information, please read this wiki page: https://github.com/Jakubson/JPremiumCleared/wiki#bedrock-support
floodgateSupport: false

# Should JPremium require to confirm a password in the register, change password and cracked commands?
# If you enable it, please do not forget to change the usage messages in the message file.
confirmPassword: false

# Should JPremium verify captcha codes which are entered by cracked players.
# If you set disable it, please also set 'captchaMapSlot' to '-1' in your JPremium configuration files on all your Spigot servers.
verifyCaptchaCode: true

# Should JPremium show a boss bar with remain time to authorisation for cracked players.
showBossBarRemainAuthorisationTimer: true

# Should JPremium keep a password when players change an account type for premium.
keepPremiumUserPasswords: false

# Should JPremium check server statuses and connect players only with online servers.
checkServerStatuses: true

# Should JPremium use the backup server when the official server is down to authorise players.
# As the backup server JPremium use CouldFlare Workers.
useBackupServer: false

# Should JPremium load user data during the login stage.
# It is an experimental feature.
loadUserProfileDataOnJoin: false

# The maximum quantity of user profiles which cracked players can register using the same IP addresses.
# When 'registerPremiumUsers' option is enabled, the limit is not apply for premium players.
maximumUserProfilesPerAddress: 2

# The maximum time (in seconds) which cracked players have for login or register.
maximumAuthorisationTime: 90

# The maximum time (in minutes) for which cracked players can start sessions?
# Sessions work only when cracked players have the same IP addresses, so it is not recommended to set the value too high.
maximumSessionTime: 1440

# The session time (in minutes) which is automatically started after cracked players login or register.
autoSessionTime: 720

# The absent time (is days) after which cracked players are automatically unregistered.
automaticUnregisterTime: 0

# The hashing algorithm which is used to hash cracked player passwords.
# There are two options: SHA256, SHA512, BCRYPT.
# All of algorithms are salted.
passwordHashingAlgorithm: SHA256

# The maximum quantity of join requests which can be processed within 3 minutes.
# If it is exceed, the next join requests are rejected.
antiBotSensitive: 120

# The safe password pattern (in regular expression). Cracked player passwords have to match to it.
safePasswordPattern: '[\S]{6,25}'

# The hostnames which players can use to connect with your BungeeCord server.
# If you want to disable it, please set the value to '[]'.
# All host names have to have ports, for example: 'acceptedHostnames: [mc.example:25565]'.
acceptedHostnames: []

# The commands which not logged cracked players can execute.
logoutUserCommands: [login, register, recoverypassword, l]

# The command aliases.
# To add more aliases for commands, please add new values using this format '<command>CommandAliases: [<alias>, <alias>, ...]', for example: 'changePasswordCommandAliases: [chpass]'.
# If you want to disable a command, you have to enter the command to the 'disabled_commands' list in your BungeeCord configuration file.
loginCommandAliases: [l]
